# version: '3.9'

# services:
#   # Client service
#   client:
#     build:
#       context: .
#       dockerfile: Dockerfile.client
#     ports:
#       - "5173:80"  # Map container port 80 to host port 5173
#     networks:
#       - app-network

#   # Server service
#   server:
#     build:
#       context: .
#       dockerfile: Dockerfile.server
#     ports:
#       - "5000:5000"
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

version: '3.9'

services:
  # Client service
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"  # Map container port 80 to host port 5173
    networks:
      - app-network

  # Server service
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
