# Stage 1: Node client
FROM node:14 AS client

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY client/package.json client/package-lock.json ./

# Install client dependencies
RUN npm install

# Copy the client application code to the container
COPY client /app/

# Build the client app
RUN npm run build


# Specify the default command to run the application
CMD ["npm", "run", "dev"]

